# Generated by Django 6.1.1 on 2026-09-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsTable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('technologies', models.TextField()),
                ('year', models.IntegerField()),
                ('url', models.TextField()),
                ('description', models.TextField()),
                ('ismain', models.IntegerField(db_column='isMain')),
            ],
            options={
                'db_table': 'projectsTable',
                'managed': True,
            },
        ),
    ]
